cache: apt
sudo: false
language: python
python:
- '3.5'
addons:
  apt:
    packages:
    - libblas-dev
    - liblapack-dev
    - gfortran
install:
- pip install -r requirements.txt
- pip install coveralls
script:
- python -m unittest discover
notifications:
  email: false
after_success:
  coveralls