cache: apt
sudo: false
language: python
python:
- '3.5'
- '3.6'
install:
- pip install -r requirements.txt
- pip install coveralls
script:
- python -m unittest discover
notifications:
  email: false
after_success:
  coveralls