cache: apt
sudo: false
language: python
python:
- '3.3'
- '3.4'
- '3.5'
addons:
  apt:
    packages:
    - libblas-dev
    - liblapack-dev
    - gfortran
before_install:
- wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- conda update --yes conda
install:
- conda install --yes python=$TRAVIS_PYTHON_VERSION pip numpy matplotlib
- pip install -r requirements_travis.txt
- pip install coveralls
script:
- python setup.py nosetests
notifications:
  email: false
after_success:
  coveralls